version: "3"

services:
    jackett:
        image: linuxserver/jackett:development
        ports:
            - 9117:9117
        volumes:
            - /storage/bin/configs:/config

    rapidbay:
        image: shnoobins/rapidbay
        environment:
            - JACKETT_HOST=http://jackett:9117
            - JACKETT_API_KEY=YOUR_API_KEY
        ports:
            - 5000:5000
        links:
            - jackett
